# Imagen Genetics Lab configuration (schema v2)
# This YAML layout mirrors the JSONC schema used by the refactored pipeline.
schema_version: 2

presets:
  # Default presets selected on startup.
  style_preset: null
  character_preset: null
  # Bias profile identifier that should exist in the profiles/ directory.
  profile_id: studio

storage:
  # Persistent artefact locations.
  database: scores.sqlite
  scores_log: scores.jsonl
  artifacts_dir: output
  catalogs:
    # Primary catalog with scene components.
    primary: catalogs/all-together.json
    # Optional catalog that exposes interactive options.
    options: catalogs/all-together.json
    # Character registry with persona presets.
    characters: catalogs/characters
  profiles:
    # Directory containing bias profiles (<id>.json).
    directory: profiles
    # Active profile file; should align with presets.profile_id.
    active: profiles/studio.json

runtime:
  prompting:
    required_terms:
      - illustration
      - watercolor
      - glossy
      - paper
      - pastel
    template_ids:
      - caption_v1
      - caption_v2
      - caption_v3
      - caption_v4
  ollama:
    url: http://localhost:11434
    model: qwen2.5:3b
    temperature: 0.55
    top_p: 0.9
    manual_mode: false
  imagen:
    model: imagen-3.0-generate-002
    person_mode: allow_adult
    guidance_scale: 0.5
  defaults:
    sfw_level: 0.6
    temperature: 0.55
    per_cycle: 2
    cycles: 10
    sleep_s: 1.0
    seed: null
  history:
    embeddings:
      enabled: true
      max_embeddings: 512
  ga:
    population: 16
    generations: 4
    keep_fraction: 0.25
    mutation: 0.15
    crossover: 0.3
    resume_best: false
    resume_top_k: 0
    resume_session: null
    resume_mix_ratio: 0.1
  feedback:
    enabled: true
    component_alpha: 0.25
    gene_alpha: 0.35
    bias_floor: 0.7
    bias_ceiling: 1.6
    component_margin: 0.12
    history: 6
    top_k: 3

scoring:
  device: auto
  batch_size: 4
  temperatures:
    default: 0.07
    clip_prompt_alignment: 0.05
    identity_consistency: 0.06
    ai_artifacts: 0.08
    visual_noise_level: 0.09
  calibration:
    style: null
    illustration: null
  weights:
    inline:
      clip: 0.2
      spec: 0.15
      illu: 0.08
      retro: 0.1
      medium: 0.1
      sensual: 0.1
      pose: 0.08
      camera: 0.05
      color: 0.05
      accessories: 0.04
      composition: 0.03
      skin_glow: 0.02
    profiles:
      table: imagen_lab/scoring/weight_profiles.yaml
      profile: default
      persist_updates: false
  auto_weights:
    enabled: true
    target: 0.88
    ema_alpha: 0.25
    momentum: 0.35
  composition_metrics: true

macro_weights:
  subject_focus: 1.0
  composition_symmetry: 1.0
  lighting_drama: 1.1
  color_vibrancy: 1.0
  nsfw_pressure: 0.8
  camera_distance: 1.0

meso_aggregates:
  pose_dynamics: 1.0
  prop_density: 1.0
  background_complexity: 1.0
  emotion_intensity: 1.0
  texture_detail: 1.0
  shot_angle: 1.0

bias_rules:
  - "subject_focus *= 1.05"
  - "!nsfw_pressure"
